[package]
name = "gravity-v2"
version = "0.1.0"
authors = ["Mikail <mikail.khan45@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
legion = "0.1.1"

[profile.dev]
opt-level = 2
